src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity('email')]
class User implements PasswordAuthenticatedUserInterface, UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $password = null;

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $token = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $logo = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    /**
     * @var Collection<int, TrickComment>
     */
    #[ORM\OneToMany(targetEntity: TrickComment::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $trickComments;

    /**
     * @var Collection<int, ChatRoomComment>
     */
    #[ORM\OneToMany(targetEntity: ChatRoomComment::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $chatRooms;

    public function __construct()
    {
        $this->trickComments = new ArrayCollection();
        $this->chatRooms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): static
    {
        $this->token = $token;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * @return Collection<int, TrickComment>
     */
    public function getTrickComments(): Collection
    {
        return $this->trickComments;
    }

    public function addTrickComment(TrickComment $trickComment): static
    {
        if (!$this->trickComments->contains($trickComment)) {
            $this->trickComments->add($trickComment);
            $trickComment->setUser($this);
        }

        return $this;
    }

    public function removeTrickComment(TrickComment $trickComment): static
    {
        if ($this->trickComments->removeElement($trickComment)) {
            // set the owning side to null (unless already changed)
            if ($trickComment->getUser() === $this) {
                $trickComment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ChatRoomComment>
     */
    public function getChatRoomComments(): Collection
    {
        return $this->chatRooms;
    }

    public function addChatRoomComment(ChatRoomComment $chatRoomComment): static
    {
        if (!$this->chatRooms->contains($chatRoomComment)) {
            $this->chatRooms->add($chatRoomComment);
            $chatRoomComment->setUser($this);
        }

        return $this;
    }

    public function removeChatRoomComment(ChatRoomComment $chatRoomComment): static
    {
        if ($this->chatRooms->removeElement($chatRoomComment)) {
            // set the owning side to null (unless already changed)
            if ($chatRoomComment->getUser() === $this) {
                $chatRoomComment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
		{% block stylesheets %}
			<link rel="stylesheet" href="{{ asset('styles/editOrDeleteButton.css') }}" type="text/css" media="all"/>
			<link rel="stylesheet" href="{{ asset('styles/app.css') }}" type="text/css">
			<link rel="stylesheet" href="{{ asset('styles/navbar.css') }}" type="text/css">
			<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		{% endblock %}

		{% block javascripts %}
			<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
			<script src="{{ asset('asset/JS/toast.js') }}"></script>
		{% endblock %}
	</head>
	<body class="container-fluid">
		{% include "Global/navbar.html.twig" %}
		{% if app.user and app.user.isVerified == false %}
			<div class="alert alert-warning alert-dismissible" role="alert">
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				<div class="alert-message">
					<strong>Votre compte n'est pas activé</strong>,
					<a href="{{ path('resend_verif') }}">renvoyer le lien d'activation</a>
				</div>
			</div>
		{% endif %}
		{% include "Global/toast.html.twig" %}
		{% block body %}{% endblock %}
	</body>
</html>

templates/chatroom.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil SnowTrick
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
{% endblock %}

{% block body %}
	<div class="text-center m-3">Espace de discussion commun à toutes les figures</div>

	{% if is_granted('IS_AUTHENTICATED') %}
		{% for label, messages in app.flashes(['error_comment', 'succes_comment']) %}
			{% for message in messages %}
				<div class="flash_{{ label }} text-center">
					{{ message }}
				</div>
			{% endfor %}
		{% endfor %}

		<form class="row justify-content-center m-3" action="{{ path('add_chatroom_comment') }}" method="POST">
			<div class="col-11 col-md-8 col-lg-6">
				<div class="input-group mb-3 justify-content-md-center">
					<input type="hidden" name="page" value="{{ page }}">
					<textarea class="form-control" aria-label="With textarea" placeholder="Laissez un commentaire ici ..." aria-describedby="button-add-comment" name="commentContent"></textarea>
					<button class="btn btn-outline-primary" type="submit" id="button-add-comment">Envoyer</button>
				</div>
			</div>
		</form>
	{% endif %}

	{% include "Utils/listComment.html.twig" with {'comments': comments}%}

	<div class="text-center m-3">
		pagination
		<div>
			{% for i in range(1, totalNumberPages) %}
				<a class="btn btn-primary" href="{{ path('chatroom', {'page': i}) }}" role="button">{{i}}</a>
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil SnowTrick
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('styles/homepage.css') }}" type="text/css" media="all"/>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script>
		let trickListLength = "{{ trickList|length }}";
	</script>
	<script src="{{ asset('asset/JS/homepage.js') }}"></script>
{% endblock %}

{% block body %}
	{% for label, messages in app.flashes %}
		{% for message in messages %}
			<div class="flash-{{ label }} text-center sucess_flash">
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}
	<div class="homepage_picture">
		<p class="catch_phrase">toujours plus haut</p>
		<img src="{{ asset('asset/pictures/snowtrick4.jpg') }}" alt="Image d'accueil"/>
		<a href="#" class="smooth_scroll_up" data-target="#trick_list">{{ ux_icon('formkit:arrowdown') }}</a>
	</div>
	{% set nbTricksPerPage = 4 %}
	<div class="trick_list row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xxl-4 g-2 m-0 d-flex justify-content-center" id="trick_list" data-nbtricksperpage={{nbTricksPerPage}}>
		{% for key, trick in trickList %}
			{% if key >= nbTricksPerPage %}
				{% set trickClass = 'hide' %}
			{% else %}
				{% set trickClass = 'show_trick' %}
			{% endif %}
			<div class="col {{trickClass}}" data-tricktarget={{(key/nbTricksPerPage) % nbTricksPerPage}}>
				<div class="col">
					<div class="card h-100">
						{% if is_granted('ROLE_ADMIN') %}
							{% include "Utils/editOrDeleteButton.html.twig" with {key: key,trickName: trick.name, trickSlug: trick.slug} only %}
						{% endif %}
						{% set oldestPicture = trick.getCoverPicture().url ?? 'snowtrick4.jpg' %}
						<img src="{{ asset('asset/pictures/' ~ oldestPicture) }}" class="card-img-top" alt="Image pour {{ trick.name }}">
						<div class="card-body">
							<h5 class="card-title">
								<a href="{{ path('trick_show', {'slug': trick.slug}) }}">
									{{ trick.name }}</a>
							</h5>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<footer>
		<button id="moreTricks" class="btn btn-success">Afficher plus de tricks</button>
		<a href="#" class="smooth_scroll_down hide" data-target="#trick_list" id="arrowUp">{{ ux_icon('formkit:arrowup') }}</a>
	</footer>
{% endblock %}

templates/trick.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	SnowTrick :
	{{trick.name}}
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('styles/trickPage.css') }}" type="text/css" media="all"/>
	<link rel="stylesheet" href="{{ asset('styles/listComment.css') }}" type="text/css" media="all"/>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script>
		const trickId = Number("{{ trick.id }}");
	</script>
	<script src="{{ asset('asset/JS/trickTemplate.js') }}"></script>
{% endblock %}

{% block body %}

	<div class="cover_img">
		<div class="trick_name">{{trick.name}}</div>
		{% if trick.getCoverPicture() %}
			{% if is_granted('ROLE_ADMIN') %}
				{% include "editOrDeleteButton.html.twig" with {key:1,'trickName': trick.name, 'trickSlug': trick.slug} %}
			{% endif %}
			<img src="{{ asset('asset/pictures/' ~ trick.getCoverPicture().getUrl()) }}" alt="Oldest picture of the trick">
		{% else %}
			<img src="{{ asset('asset/pictures/' ~ trick.trickPictures|first.getUrl()) }}" alt="Oldest picture of the trick">
		{% endif %}
	</div>

	<div class="text-center m-4" id="show_pictures_videos_list_button">
		<button class="btn btn-primary show_pictures_videos_list" type="button">
			Afficher les photos et vidéos
		</button>
	</div>

	<div class="pictures_videos_list hidden" id="pictures_videos_list">
		<div class="trick_list row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xxl-4 g-2 m-0 d-flex justify-content-center" id="trick_list">
			{% for picture in trick.trickPictures %}
				<div class="col">
					<div class="card h-100">
						<img src="{{ asset('asset/pictures/' ~ picture.url) }}"/>
					</div>
				</div>
			{% endfor %}
			{% for video in trick.trickVideos %}
				<div class="col">
					<div class="card h-100">
						{% if video.isExternalUrl() %}
							<iframe src={{video.url}} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
						{% else %}
							<video controls>
								<source src="{{ asset('asset/videos/' ~ video.url) }}" type="video/mp4">
								Votre navigateur ne supporte pas la vidéo HTML5.
							</video>
						{% endif %}
					</div>
				</div>
			{% endfor %}
		</div>
	</div>


	<div class="description text-center m-3">
		<h5>Description</h5>
		{{trick.description}}
	</div>

	<div class="trick_infos m-3 row justify-content-center gx-2">
		<div class="category col col-lg-2">
			<span class="badge text-bg-dark">Catégorie :
				{{trick.trickGroup.name}}</span>

		</div>
		<div class="created_at col col-lg-2">
			<span class="badge text-bg-dark">créé le :
				{{ trick.createdAt|date('d/m/Y') }}</span>
		</div>
		{% set hasBeenUpdated = trick.updatedAt ? trick.updatedAt|date('d/m/Y') : null %}
		{% if hasBeenUpdated is not null %}
			<div class="updated_at col col-lg-2">
				<span class="badge text-bg-dark">mis à jour :
					{{ trick.updatedAt|date('d/m/Y') }}</span>
			</div>
		{% else %}
			<div class="updated_at col col-lg-2">
				<span class="badge text-bg-dark">jamais mis à jour</span>
			</div>
		{% endif %}
	</div>

	{% if is_granted('IS_AUTHENTICATED') %}
		{% for label, messages in app.flashes(['error_comment', 'succes_comment']) %}
			{% for message in messages %}
				<div class="flash_{{ label }} text-center">
					{{ message }}
				</div>
			{% endfor %}
		{% endfor %}

		<form class="row justify-content-center" action="{{ path('add_trick_comment') }}" method="POST">
			<div class="col-11 col-md-8 col-lg-6">
				<div class="input-group mb-3 justify-content-md-center">
					<input type="hidden" name="trick_id" value="{{ trick.id }}">
					<input type="hidden" name="trick_slug" value="{{ trick.slug }}">
					<textarea class="form-control" aria-label="With textarea" placeholder="Laissez un commentaire ici ..." aria-describedby="button-add-comment" name="commentContent"></textarea>
					<button class="btn btn-outline-primary" type="submit" id="button-add-comment">Envoyer</button>
				</div>
			</div>
		</form>
	{% endif %}


	<h6 class="text-center m-4">Commentaires de la communauté</h6>
	<ul class="list-group container mb-3" id="more_comments_container">
		{% for comment in comments %}
			<li class="list-group-item d-flex trick_comment_item">
				{% if comment.getUser().getLogo() is not null %}
					<img src="{{comment.getUser().getLogo()}}" class="rounded-circle" style="width: 50px;" alt="Avatar"/>
				{% else %}
					<div class="no_avatar" alt="Avatar">{{comment.getUser().getName()|slice(0, 2)}}</div>
				{% endif %}
				<div>{{ comment.content }}
				</br>
				<span>le
					{{ comment.createdAt|date('d/m/Y') }}</span>
				<span>par
					{{ comment.user.getName() }}</span>
			</li>
		</div>
	</li>
{% else %}
	<li class="list-group-item">Aucun commentaire pour ce trick.</li>
{% endfor %}</ul>{% if (trick.comments|length <= 5) is same as(false) %}
{% set test = comments|length %}<div class="text-center m-4" id="load-more-comments-container">
	<button type="button" class="btn btn-primary" id="load-more-comments">Afficher plus de commentaires</button>
</div>{% endif %}{% endblock %}